import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/general/user/html/login.html');
  await page.locator('html').click();
  await page.goto('http://localhost:3000/general/html/home.html');
  await page.getByRole('button', { name: 'Chatbot Icon' }).click();
  await page.getByPlaceholder('Ask me anything...').fill('Hello');
  await page.getByPlaceholder('Ask me anything...').press('Enter');
  await page.getByRole('button', { name: 'Send', exact: true }).click();
  await page.getByPlaceholder('Ask me anything...').click();
  await page.getByPlaceholder('Ask me anything...').fill('When the library open?');
  await page.getByPlaceholder('Ask me anything...').press('Enter');
  await page.getByPlaceholder('Ask me anything...').click();
  await page.getByPlaceholder('Ask me anything...').fill('When the library open?');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').press('ArrowLeft');
  await page.getByPlaceholder('Ask me anything...').fill('When will the library open?');
  await page.getByPlaceholder('Ask me anything...').click();
  await page.getByPlaceholder('Ask me anything...').press('ArrowRight');
  await page.getByPlaceholder('Ask me anything...').press('ArrowRight');
  await page.getByPlaceholder('Ask me anything...').press('ArrowRight');
  await page.getByPlaceholder('Ask me anything...').fill('When will the library be open?');
  await page.getByRole('button', { name: 'Send', exact: true }).click();
  await page.getByRole('button', { name: 'Library Hours' }).click();
  await page.getByRole('button', { name: 'Membership' }).click();
  await page.getByRole('button', { name: 'Search Book' }).click();
  await page.getByPlaceholder('Ask me anything...').click();
  await page.getByPlaceholder('Ask me anything...').fill('Gasby');
  await page.getByRole('button', { name: 'Send', exact: true }).click();
  await page.getByPlaceholder('Ask me anything...').click();
  await page.getByPlaceholder('Ask me anything...').fill('agame');
  await page.getByPlaceholder('Ask me anything...').click();
  await page.getByPlaceholder('Ask me anything...').dblclick();
  await page.getByPlaceholder('Ask me anything...').fill('great');
  await page.getByRole('button', { name: 'Send', exact: true }).click();
  await page.getByRole('button', { name: 'Search Book' }).click();
  await page.getByPlaceholder('Ask me anything...').click();
  await page.getByPlaceholder('Ask me anything...').fill('great');
  await page.getByRole('button', { name: 'Send', exact: true }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Click here to view details ^^' }).click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: 'Book Collection' }).click();
});